export let colors = {
  csBlue:               {hex:'#003E52'},
  csBlueDark:           {hex:'#00283c'},
  csBlueDarker:         {hex:'#00212b'},
  csBlueLight:          {hex:'#006f84'},
  csBlueLighter:        {hex:'#00b6cd'},
  csBlueLightDesat:     {hex:'#2c9aa8'},
  csOrange:             {hex:'#ff8400'},
  darkCsOrange:         {hex:'#d97500'},
  lightCsOrange:        {hex:'#ffa94d'},
  // menuBackground:       {hex:'#00263e'},
  menuBackground:       {hex:'#00283c'},
  menuBackgroundDarker: {hex:'#00172c'},
  // menuBackgroundDarker: {hex:'#001122'},
  menuText:             {hex:'#fff'},
  menuTextSelected:     {hex:'#2daeff'},
  menuTextSelectedDark: {hex:'#2472ad'},
  white:                {hex:'#fff'},
  black:                {hex:'#000'},
  gray:                 {hex:'#ccc'},
  notConnected:         {hex:'#00283c'},
  darkGray:             {hex:'#555'},
  darkGray2:            {hex:'#888'},
  lightGray2:           {hex:'#dedede'},
  lightGray:            {hex:'#eee'},
  purple:               {hex:'#8a01ff'},
  darkPurple:           {hex:'#5801a9'},
  darkerPurple:         {hex:'#2a0051'},
  blue:                 {hex:'#0075c9'},
  blue2:                {hex:'#2698e9'},
  green:                {hex:'#a0eb58'},
  lightGreen:           {hex:'#caff91'},
  darkGreen:            {hex:'#1f4c43'},
  green2:               {hex:'#4cd864'},
  orange:               {hex:'#ff953a'},
  red:                  {hex:'#ff3c00'},
  darkRed:              {hex:'#cc0900'},
  menuRed:              {hex:'#e00'},
  iosBlue:              {hex:'#007aff'},
  iosBlueDark:          {hex:'#002e5c'},
  lightBlue:            {hex:'#a9d0f1'},
  lightBlue2:           {hex:'#77c2f7'},
  blinkColor1:          {hex:'#2daeff'},
  blinkColor2:          {hex:'#a5dcff'},
  random: () => {}
};
